import { FavoritesNavBtn } from "@/components/Favorites/FavoritesNavBtn";
import { Provider } from "@/components/ui/provider";
import { Box, Button, Container, Theme } from "@chakra-ui/react";
import type { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <Theme appearance="light">
            <Box
              as="header"
              height="45px"
              position="sticky"
              top="0"
              zIndex="100"
              width="100%"
              bgColor="white"
              borderBottom="1px solid"
              borderColor="gray.200"
            >
              <Container
                maxW="container.xl"
                height="100%"
                display="flex"
                alignItems="center"
              >
                <Link href={"/"} style={{ textDecoration: "none" }}>
                  <Button variant="outline" size="sm">
                    Home
                  </Button>
                </Link>
                <FavoritesNavBtn to="/favorites" />
              </Container>
            </Box>
            <Suspense>
              <Container
                maxW="container.xl"
                px={{ base: "4", md: "6", lg: "8" }}
                py="4"
              >
                {children}
              </Container>
            </Suspense>
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
