import { Provider } from "@/components/ui/provider";
import { Theme } from "@chakra-ui/react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <Theme appearance="light">{children}</Theme>
        </Provider>
      </body>
    </html>
  );
}
